name: Update Version in repoB

on:
  workflow_dispatch:
    inputs:
      rel_version:
        description: 'Release version'
        required: true

jobs:
  update-repoB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoA
        uses: actions/checkout@v3

      - name: Checkout repoB
        uses: actions/checkout@v3
        with:
          repository: elena-kolevska/repoB
          token: ${{ secrets.PAT_TOKEN }}  # Use personal access token
          path: repoB

      - name: Update Version in repoB
        run: |
          echo "${{ inputs.rel_version }}" > repoB/config/dapr_runtime.version

      - name: Commit and Push Changes to repoB
        run: |
          cd repoB
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add config/dapr_runtime.version
          git commit -m "Update dapr_runtime.version to ${{ inputs.rel_version }}"
          git push
