name: Update Version in repoB

on:
  workflow_dispatch:
    inputs:
      rel_version:
        description: 'Release version'
        required: true

jobs:
  update-repoB:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          repositories: "repoB"

      - name: Checkout repoB
        uses: actions/checkout@v3
        with:
          repository: elena-kolevska/repoB
          token: ${{ steps.get_workflow_token.outputs.token }}  # Use the generated token
          path: repoB
      
      - name: Parse release version and set REL_VERSION and LATEST_RELEASE
        run: python test-infra/.github/scripts/get_release_version.py ${{ github.event_name }}

      - name: Update Version in repoB
        run: |
          echo "Env rel version: ${{ env.REL_VERSION }}"
          echo "Rel version: ${REL_VERSION}"
          # echo "${{ env.REL_VERSION }}" > test-infra/config/dapr_runtime.version
          # echo "${{ inputs.rel_version }}" > repoB/config/dapr_runtime.version

      # - name: Commit and Push Changes to repoB
      #   run: |
      #     cd repoB
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     git add config/dapr_runtime.version
      #     git commit -m "Update dapr_runtime.version to ${{ inputs.rel_version }}"
      #     git push

